import { BlueMenu } from '@/components/UI/BlueMenu/BlueMenu'
import Head from 'next/head'

export default function Layout({ children }: { children: React.ReactNode }) {
    return (<>
        <Head>
            <title>Все Вакансии компании FinTechPro</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/цветной лого прозрачный 1.png" />
        </Head>
        <main>
            <BlueMenu />
            {children}
        </main >
    </>
    )
}
