import Head from 'next/head'
import React from 'react'

import { Navigation } from '@/components/Modules/Navigation/Navigation'




export default function Layout({ children }: { children: React.ReactNode }) {
    return (<>
        <Head>
            <title>FinTechPro</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main style={{ background: '#ccc', height: '100vh' }} >
            <Navigation />
            {children}
        </main>
    </>
    )
}
